---
- hosts: localhost
  gather_facts: no
  vars:
    input_file: 'products.json'
  tasks:
    - name: Read input file
      include_vars:
        file: "{{ input_file }}"
        name: data

    - name: Remove 'album' attribute
      set_fact:
        data: "{{ data.products | map('product') | list }}"
      vars:
        product: "{{ item | default({}) | combine({ 'id': item.id, 'name': item.name, 'repository_count': item.repository_count }) }}"
      loop: "{{ data.products }}"

    - name: Register result
      set_fact:
        result: "{{ data }}"