---
- name: Ansible playbook to convert JSON to YAML
  hosts: localhost
  gather_facts: false
  vars:
    debug_playbook: true
  tasks:
    - name: Read JSON file
      ansible.builtin.set_fact:
        products_json: "{{ lookup('file', 'products.json') }}"

    - name: Print JSON file content
      ansible.builtin.debug:
        var: products_json
      when: debug_playbook

    - name: Convert JSON to YAML
      ansible.builtin.set_fact:
        yaml_content: "{{ products_json | to_nice_yaml }}"

    - name: Print YAML content
      ansible.builtin.debug:
        var: yaml_content

    - name: Write YAML content to file
      ansible.builtin.copy:
        content: "{{ yaml_content }}"
        dest: "output.yaml"
        mode: '0644'
