---
- name: Ansible playbook to convert JSON to YAML
  hosts: localhost
  gather_facts: false
  vars:
    debug_playbook: false
  tasks:
    - name: Read products.json file
      ansible.builtin.set_fact:
        products_json: "{{ lookup('file', 'products.json') | from_json }}"

    - name: Read repositories.json file
      ansible.builtin.set_fact:
        repositories_json: "{{ lookup('file', 'repositories.json') | from_json }}"

    - name: Print JSON file content
      ansible.builtin.debug:
        var: products_json
      when: debug_playbook

    - name: Print JSON file content
      ansible.builtin.debug:
        var: repositories_json
      when: debug_playbook

    - name: Create output.yaml file
      ansible.builtin.template:
        src: output_template.j2
        dest: "output.yaml"
      when: not debug_playbook
