products:
  - id: 1
    name: Product 1
    repository_count: 2
    repositories:
      - id: 1
        name: Repository 1
      - id: 2
        name: Repository 2
  - id: 2
    name: Product 2
    repository_count: 3
    repositories:
      - id: 1
        name: Repository 1
      - id: 2
        name: Repository 2
      - id: 3
        name: Repository 3
  - id: 3
    name: Product 3
    repository_count: 0
  - id: 4
    name: Product 4
    repository_count: 1
    repositories:
      - id: 1
        name: Repository 1
  - id: 5
    name: Product 5
    repository_count: 4
    repositories:
      - id: 1
        name: Repository 1
      - id: 2
        name: Repository 2
      - id: 3
        name: Repository 3
      - id: 4
        name: Repository 4
  - id: 6
    name: Product 6
    repository_count: 0
  - id: 7
    name: Product 7
    repository_count: 5
    repositories:
      - id: 1
        name: Repository 1
      - id: 2
        name: Repository 2
      - id: 3
        name: Repository 3
      - id: 4
        name: Repository 4
      - id: 5
        name: Repository 5
  - id: 8
    name: Product 8
    repository_count: 0
  - id: 9
    name: Product 9
    repository_count: 1
    repositories:
      - id: 1
        name: Repository 1
  - id: 10
    name: Product 10
    repository_count: 2
    repositories:
      - id: 1
        name: Repository 1
      - id: 2
        name: Repository 2