products:
  - id: 1
    name: Product 1
    repository_count: 2
  - id: 2
    name: Product 2
    repository_count: 3
  - id: 3
    name: Product 3
    repository_count: 0
  - id: 4
    name: Product 4
    repository_count: 1
  - id: 5
    name: Product 5
    repository_count: 4